### ISSUE TITLE
[Spike] - Update color architecture of Spark Theme

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1071]
see 👉 https://github.com/adevinta/spark-tokens/pull/56 for reference
also 👉 https://docs.google.com/spreadsheets/d/12bAgOwqZ4HCt4vInfMsCT34pUxOZIQtEAP4RIIiqD3Q/edit#gid=0
figma 👉 https://www.figma.com/file/XKArFiHjh9J1sR8aezjxmE/Colours-for-Spark?type=design&node-id=388-313292&mode=design&t=yTbt5X8nknOEJrj1-0

### Prerequisites:
Before starting out those tasks, we will need:
- [x] to have the Figma updated

### Description:
In summary, the following steps need to be taken:
- [x] 1. Integrate `basic` and `accents` tokens into the color scheme

**starting from this point, we will create a canary branch to handle the tasks below 👇**

- [x] 2. Rename `primary` to `main`, and `secondary` to `support` https://github.com/adevinta/spark/pull/1102
- [ ] 3. Once the theme is updated, update all components accordingly to the new theme structure.
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1073
- [ ] https://github.com/adevinta/spark/issues/1074
- [ ] https://github.com/adevinta/spark/issues/1074
```

```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1073
- [ ] https://github.com/adevinta/spark/issues/1074
- [ ] https://github.com/adevinta/spark/issues/1089
- [ ] https://github.com/adevinta/spark/issues/1091
- [ ] https://github.com/adevinta/spark/issues/1085
- [ ] https://github.com/adevinta/spark/issues/1086
- [ ] https://github.com/adevinta/spark/issues/1087
- [ ] https://github.com/adevinta/spark/issues/1088
- [ ] https://github.com/adevinta/spark/issues/1090
- [ ] https://github.com/adevinta/spark/issues/1092
- [ ] https://github.com/adevinta/spark/issues/1093
- [ ] https://github.com/adevinta/spark/issues/1094
- [ ] https://github.com/adevinta/spark/issues/1095
```
