### ISSUE TITLE
Clean the radio button label component in figma

### ISSUE THREAD

**Issue by lauragautheron** [adevinta/spark#1315]
when we changed the documentation for the radio button component, we came upon 2 pblms

- the caption text should be hug and not fixed width -> there is a fix to be done on the Label component
- the component "Radio Button Label" isn't clean (uses too many frames and a wrong naming) : https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/branch/YTv3DZfyknS6xMKZZhxXlv/Spark-Components?type=design&node-id=5%3A1534&mode=design&t=Paxvc3XPOD8LEvKh-1
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1319
- [x] frame naming
- [x] communicate decision to designers
- [x] create polaris components
- [x] polaris file : copy screen, unlink to keep a trace of production
- [ ] then merge
- [ ] then rewrite labels
```

**Comment by lauragautheron** [comment]
@Bibisirius will take care of the label component and I will take care of the naming, so we should split this task in 2
