### ISSUE TITLE
[Component] Progress tracker

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1362]
Request: https://adevinta.slack.com/archives/C059UCP6B63/p1693309929470559

[Spec sheet](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=12212-6713&mode=design)

- [x] Clarify naming: Progress indicator vs. Step indicator: Final decision: Progress tracker
- [x] Rename the slack channel: Progress tracker 
- [x] Add to Component overview in ZeroHeight
- [x] Create Spec
- [x] Create ZeroHeight documentation
