### ISSUE TITLE
Help prioritise new list of Q4 components

### ISSUE THREAD

**Issue by lauragautheron** [adevinta/spark#1409]
```[tasklist]
### Tasks
- [x] new list
- [x] contact product director or ludo
- [ ] contact FT who requested component
- [ ] finalise order
```

**Comment by lauragautheron** [comment]
- [x] Multiselect 
    - [ ] Web (Identity) - asap -> communicate that they can do it with chips

- [x] Checkbox
    - [ ] All (Search) - asap - veulent la pastille bleue des filtres -> composant Polaris

- [x] Textfield : planned for Q3
    - All (Adlife) - needed in Q3
    - iOS (Identity) - needed in Q3
    - [ ] Communicate status of each platform : everything ok except for iOS UI kit (?)

- [x] Progress Bar - planned for Q3
    - All (Adlife) - needed in Q3


Select / Dropdown
    - All Dropdown menus (Pro ads) use case on ad detail - needed in Q4
    - All Select / multiselect (Adlife) - needed in Q3
    - Web Select (Panda) - needed in Q4
    - AND country-specific telephone area code dropdown (Pro Orange team) - asap

- [ ] Modal - planned for Q3 -> confident or not ?
    - All Modal (Pro ads) use case on ad detail - needed in Q4


Drawer
    - Web  (Panda)  - asap

Snackbar
    - Web (Identity) - asap

Combobox
    - All (Identity) - asap (auto compliance component for address field)

Progress steps
    - AND (Pro Orange team) - asap

Accordion / collapsible
    - Web (FT Holidays) - needed in Q4

**Comment by lauragautheron** [comment]
@thomas-leguellec has there been already communication towards the Identity team to tell them that they should use chips for multi-select ?

and for the textfield in iOS, in the list of components, everything is ok except for the UI Kit, I'm not sure what it means : is it available or not ? and has there already been a communication or do you want me to do it ?

**Comment by lauragautheron** [comment]
I would move at the top of Q4 :
- dropdown / select

and would bring a bit down the progress indicator (but not sure what it is)

**Comment by lauragautheron** [comment]
Ok so 

- I can communicate to Identity on the multi select and the Textfield for iOS (tell them it's planned soon but won't be done in Q3)
- I would suggest to move up the Select component to the top of the list, after the modal
- I will check this with Samantha Chahabi

- The modal is really important too, when do you think we will be able to deliver it (estimate) ?

@thomas-leguellec cc @turolopezsanabria
