### ISSUE TITLE
Outline Design components must have transparent background [Web]

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1423]
✅ All components must have a background transparent in outline versions
✅ Tabs have a background transparent too

**Task**
- Apply a background `transparent` to all components on rest/enabled 
- Don't change the current styles for hover, active, disabled, focus, etc. The current definition is still valid for the other states  

**Components affected**

- [x] button
- [x] iconButton
- [ ] tab
- [x] tag
- [x] chip

**Comment by elisa-hery** [comment]
Background was only updated for `tab` and `tag` (for the other ones it was already done).
Tested and validated : 

- [x] visual quality (appropriates variable tokens)
- [x] states and variations
- [x] browser compatibility (safari &chrome)

Hover invisibility will be handled later (slack thread [here](https://adevinta.slack.com/archives/C04LNCEMMUN/p1695297967112529?thread_ts=1695112295.302909&cid=C04LNCEMMUN))

@acd02 FYI
