### ISSUE TITLE
[Figma components] Update components status

### ISSUE THREAD

**Issue by lauragautheron** [adevinta/spark#1569]
```[tasklist]
### Tasks
- [ ] N/A for ios popover : what do we write ? native ?
- [ ] experimental android : Spark capsule to embed Brikke component (only for Android) does it mean that it's ready ?
- [ ] alert dialog : check in ZH but not published in figma
```

**Comment by lauragautheron** [comment]
updated : badge status

question : what do we do if for iOS it's ready in UI kit but not swift ?

could
Radio-Button 🖥️🤖🍎(iOS : UI kit only)

be a solution ?
