### ISSUE TITLE
[Component] Rating

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#1577]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/pull/1605
- [ ] https://github.com/adevinta/spark/pull/1618
- [ ] https://github.com/adevinta/spark/pull/1642
- [ ] https://github.com/adevinta/spark/pull/1636
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Does this ticket need to be tested ? | yes
Does this ticket need to be design reviewed ? | yes
Referent designer : | Laura
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7792-7244&mode=design&t=ZZFY1rwPpukfrZpN-0)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating)
Snapshots scenarii : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating#Rating-snapshots)
demo app : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating#Rating-demo-app-configurator)

**Comment by acd02** [comment]
👋 , hello @elisa-hery , actually, the Rating component has already been reviewed and (design) approved by @lauragautheron 👍

**Comment by elisa-hery** [comment]
Thanks @acd02 , I know this one is already advanced, it was just a test for the "testing template"

**Comment by soykje** [comment]
@elisa-hery Sorry for issue being closed after merging first of two PRs... I reopen it, here is the last one for testing purpose: https://github.com/adevinta/spark/pull/1618

**Comment by elisa-hery** [comment]
@soykje @acd02 here are my comments : 

1. using **keyboard navigation** we can have a rate of 0/5 and it should not be possible

https://github.com/adevinta/spark/assets/142396647/05ab9699-2c30-4f73-a260-4c9c1979ecd7

2. **on mobile, for input rating**, when I click on a star, stars stay in the hover state. I have to click outside the rating component to make them back to selected state. Is it the expected behavior ?  See video below ⬇️ 

https://github.com/adevinta/spark/assets/142396647/b5b7b911-2faf-4811-90a1-56757a4d2e61

2. I've seen that you provide **3 sizes** but the specs mention "there is no need to block the size of the icons on the developer side". Is it on purpose ? Maybe you had to define sizes ?

We can discuss it live if you prefer 😊

**Comment by soykje** [comment]
> 1. using keyboard navigation we can have a rate of 0/5 and it should not be possible

Why? We can't do it with mouse or touch events, but there is no limitation on keyboard. Also this behaviour is agreed on specs, if I understood correctly: [here](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=11013-937&mode=design&t=YinWtZpiozUMuK06-4)

> 2. on mobile, for input rating, when I click on a star, stars stay in the hover state. I have to click outside the rating component to make them back to selected state. Is it the expected behavior ?

I'll look on this, thx! :+1: 

> 3. I've seen that you provide 3 sizes but the specs mention "there is no need to block the size of the icons on the developer side". Is it on purpose ? Maybe you had to define sizes ?

There may be a misunderstanding here: specifications define three sizes, with a mention of when they should be used (display or input cases). The "here is no need to block the size of the icons on the developer side" means (to me?) that we don't have to link both size and display/input mode properties in our API. It's up to the developper, in its implementation, to follow the design guidelines. But I'll be happy to discuss, if things need to be clarified :+1:

**Comment by elisa-hery** [comment]
> 1. using keyboard navigation we can have a rate of 0/5 and it should not be possible

conclusion : **we want rating from 1 to 5, even for keyboard navigation** 
action : @soykje and @acd02 will prevent 0/5 notation (I'm moving the ticket to dev column) and @lauragautheron has updated the accessibility spec that was not clear.

> 2. on mobile, for input rating, when I click on a star, stars stay in the hover state. I have to click outside the rating component to make them back to selected state. Is it the expected behavior ?

Seen with @soykje @acd02 and @lauragautheron : this behaviour is not a prblem + it would be really heavy to change it so --> we keep as it is ✅ 

> 3. I've seen that you provide 3 sizes but the specs mention "there is no need to block the size of the icons on the developer side". Is it on purpose ? Maybe you had to define sizes ?

conclusion : we keep the 3 sizes
action : @lauragautheron updated the spec ✅

**Comment by soykje** [comment]
Expected changes on keyboard interaction are included there: https://github.com/adevinta/spark/pull/1642

**Comment by soykje** [comment]
Updated environment for testing/review purpose: https://spark-5uda4jwjp-spark-team.vercel.app/?path=/docs/getting-started--docs

**Comment by lauragautheron** [comment]
small remark on the demo( not on the component)
<img width="975" alt="Capture d’écran 2023-11-17 à 09 55 07" src="https://github.com/adevinta/spark/assets/139351490/cf074660-13e9-46a2-9ac1-719237683d17">

could you make the example for this in the input size (since it's interactive) ? so that the guideline is not confusing for people

otherwise it's all good to me !
