### ISSUE TITLE
[Component] Progress tracker

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#1581]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1696
- [ ] https://github.com/adevinta/spark/pull/1714
- [ ] https://github.com/adevinta/spark/pull/1758
- [ ] https://github.com/adevinta/spark/pull/1765
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | moderate
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX 
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=12212-6713&mode=design&t=FvppNKarxpA4HxdE-0)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker#Progress+tracker-demo-app-configurator)

**Comment by soykje** [comment]
@elisa-hery @JeremiasUX Here is the testing URL : https://spark-40nikjmyx-spark-team.vercel.app/?path=/docs/experimental-progresstracker--docs

**Comment by elisa-hery** [comment]
@soykje I've got some comments / questions ! 

1. I noticed a bug when clicking from step 2 to step 1, the steps are going crazy (see video) 
https://github.com/adevinta/spark/assets/142396647/b9ad6f2a-90db-4161-ab23-00d7506a3ec7

2. I don't understand the state of progress indicator when you can hover them, they are focusable, but not selectable
https://github.com/adevinta/spark/assets/142396647/41c2ae6a-4180-40c0-952e-70980837d7cd

3. vertical alignement between text & progress indicator does not seem same as in the specs ⬇️ 
![Capture d’écran 2024-01-04 à 18 19 30](https://github.com/adevinta/spark/assets/142396647/e7b585c1-dc6d-4bc5-8995-2253acb6a5d4)


4. for "long" progress label, text should go next line but it doesn't (see specs ⬇️ ), we could see with designers if it matters for V1 or not
![Capture d’écran 2024-01-04 à 18 31 10](https://github.com/adevinta/spark/assets/142396647/9917d018-45f5-4735-b0fd-9b351da07061)

5. a remark : I cannot really check the functional of this component since in the storybook we don't see any content switching between steps.

Let's talk about it on meet it will be easier, WDYT ?

**Comment by elisa-hery** [comment]
After meeting with @soykje : 
1. @soykje is working on the fix
2. on storybook, components are hoverable & clickable without any action behind because events are **entirely** handled by users ✅ 
3. let's wait for @JeremiasUX 's comment
4. progress label on horizontal orientation are adaptable : if the component is squeezed, is goes to line (see example below). User can also decide a max-width for progress label ✅ 
![Capture d’écran 2024-01-05 à 10 33 00](https://github.com/adevinta/spark/assets/142396647/28015191-9b4e-4520-90c8-98b1bd65c85a)

5. As I wrote in 2., event handling is totally handled by user, so developers didn't see any interest to add an examples in storybook. I think it would have been useful but it's not blocking.

**Comment by soykje** [comment]
@elisa-hery On the **1.** the fix has just been done 👍

**Comment by elisa-hery** [comment]
@soykje is the fix on the same ariane link as mentioned above ? Because I still can see the bug

**Comment by soykje** [comment]
Sorry, I forgot to share the new test link: https://spark-7wsocrlls-spark-team.vercel.app/?path=/docs/experimental-progresstracker--docs 🙏

**Comment by elisa-hery** [comment]
ok it's validated for me @soykje  ✅ 
Let's see how design review goes (especially about vertical alignment)

**Comment by JeremiasUX** [comment]
From visual side everything looks good. @soykje and I discussed the vertical alignment beforehand, as it was not possible to achieve the result documented in the spec.

Question:
- Can users change the length of the track independent of the text?

**Comment by soykje** [comment]
> Can users change the length of the track independent of the text?
This was not a specified behaviour. Tracks lenght depends on label content/size and/or on component's size.

**Comment by JeremiasUX** [comment]
Looks good to me ✅
