### ISSUE TITLE
[Chips] Add on the spec the possibility of having a select & Update Chip-selected 

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1601]
The notion of a 'select' chip is missing from ZH spark. It should be added to know that it exists.
Ref: [URL (storybook)](https://sparkui.vercel.app/iframe.html?id=components-chip--selection&viewMode=story)

![Image](https://github.com/adevinta/spark/assets/139967199/1fe2018d-a912-40b4-82bc-c4bb3df6b9e9)

```[tasklist]
### Tasks
- [x] Update doc Figma & ZH
- [ ] Update component: Add possibility to have 1 clear icon & the arrow for select version
- [x] Update the outline color iso container (label)
```

**Comment by Bibisirius** [comment]
Stand by 
**Version selection**
The use of chips on Polaris may not be optimal. We need to find a solution together and then share it

**Comment by Bibisirius** [comment]
**Web**
Possible to have a chip that opens a drawer or a popover to select a list

**Android**
Same as Web

**iOS**
N/A

**Next step:**

- Remove this case on the storybook and Figma specs. It is not recommended to have 2 elements to avoid a11y issues.
-  No action required on the chip component (ticket done)
- Communicating in Gathering
