### ISSUE TITLE
Add "inset" prop to remove internal paddings

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1646]
There is a common use case in Polaris where users want to have a picture within the Dialog or Drawer (or Popover) component that takes up the full width.

Currently, achieving this requires **overriding** the internal padding of the component. To prop would make this use case easier and more intuitive.

When set to `true`, this prop would remove the internal padding of the component, allowing for a full-width image or content.
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1652
- [ ] https://github.com/adevinta/spark/issues/1653
- [ ] https://github.com/adevinta/spark/issues/1654
```
