### ISSUE TITLE
[Design Spec] Dropdown - Select component

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1698]
Link to spec: https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=16619-4432&mode=design

```[tasklist]
### Tasks
- [x] Check spec on Figma
- [x] Create a spec on Zeroheight
- [x] Create the component
```

**Comment by Bibisirius** [comment]
Figma Spec : [Link](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=16619-4433&mode=design&t=czc1WdYtiRoJj0si-11)
ZH spec: [Link](https://adevinta.zeroheight.com/styleguide/s/100904/p/85c535-select/b/48febf)

**Comment by Bibisirius** [comment]
- [ ] What about the “read only”? ([Jeremias David](mailto:jeremias.david@adevinta.com))
- [ ] Unify the frame name for maintain the copy ([Christian Jimenez](mailto:christian.jimenez@adevinta.com))
- [ ] Should we unify clear and lead icons on alignment, spacing and sizing? ([Jordi Catalán](mailto:jordi.catalan@adevinta.com))

**Comment by ChrisDesignOps** [comment]
⚠️ Reviewed. Some changes suggested on the Figma Branch

**Comment by ChrisDesignOps** [comment]
✅ Reviewed & approved in the Figma branch
