### ISSUE TITLE
[Design Spec/Component] Dropdown Menu/Popover

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1699]
Spec sheet: https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=923-19403&mode=design

```[tasklist]
### Tasks
- [x] Refine Spec Figma
- [x] Create Spec ZeroHeight
- [x] Create a component Figma (Review)
```

**Comment by Bibisirius** [comment]
- Spec ZH : [Link](https://zeroheight.com/1186e1705/v/latest/p/323b83-dropdown)
- Spec Figma: [Link](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=46530-8049&mode=design&t=aakm8E2sAK82Vu4B-11)

**Comment by Bibisirius** [comment]
Should we unify border-radius between Dropdown & Select? (8 > 16) ? Jordi request

**Comment by Bibisirius** [comment]
The component is ready for review @ChrisDesignOps @JeremiasUX @jcatdom : [Link](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/branch/1KTP0YmHv8UyzTvkMtURF2/Spark-Components?node-id=14547-46010&review-number=37&t=ouh786drGecHpY8J-11)

**Comment by ChrisDesignOps** [comment]
⚠️ Reviewed. Some little changes suggested on Figma and for me it will be perfect :)
