### ISSUE TITLE
[Component] Dropdown

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#1726]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1669
- [ ] https://github.com/adevinta/spark/issues/1661
- [ ] https://github.com/adevinta/spark/issues/1673
- [ ] https://github.com/adevinta/spark/issues/1670
- [ ] https://github.com/adevinta/spark/issues/1680
- [ ] https://github.com/adevinta/spark/issues/1697
- [ ] https://github.com/adevinta/spark/issues/1682
- [ ] https://github.com/adevinta/spark/issues/1681
- [ ] https://github.com/adevinta/spark/issues/1684
- [ ] https://github.com/adevinta/spark/issues/1685
- [ ] https://github.com/adevinta/spark/issues/1687
- [ ] https://github.com/adevinta/spark/issues/1686
- [ ] https://github.com/adevinta/spark/issues/1719
- [ ] https://github.com/adevinta/spark/issues/1782
```

**Comment by thomas-leguellec** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1697
- [ ] https://github.com/adevinta/spark/issues/1682
- [ ] https://github.com/adevinta/spark/issues/1681
- [ ] https://github.com/adevinta/spark/issues/1684
- [ ] https://github.com/adevinta/spark/issues/1685
- [ ] https://github.com/adevinta/spark/issues/1687
- [ ] https://github.com/adevinta/spark/issues/1686
- [ ] https://github.com/adevinta/spark/issues/1719
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | to define
Does this ticket need to be design reviewed ? | yes
Referent designer : | ?
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=923-19403&mode=design&t=yhjBUkzyAUuyp1MN-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1tJClPzFgaZKtgj05iPLosltiRel7PQreEykLDajGjCc/edit#gid=316822420)
UATs : | [to add]()
configurator : | [to add]()

**Comment by elisa-hery** [comment]
List of bugs (and resolution status) is [here](https://docs.google.com/spreadsheets/d/1-wUKejjCAblIpIkE3i7n1dACB3k9qq-kND285N4WwSw/edit#gid=139525665)
