### ISSUE TITLE
[Popover] Should we add a paragraph and intent colour on popovers?

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1876]
**Should we add a paragraph on popovers?**
In most cases, only 1 title and 1 paragraph are used in a popover.
To make it easier to implement this case and to move on more quickly: should we include a paragraph by default in the popover?
✅ Yes, the request makes sense

**Do we provide intent colour for popover?**
✅ Yes, the request makes sense

```[tasklist]
### Task
- [x] Add props in the Figma component to allow the most common uses
- [x] @JeremiasUX To check with Amir if "container" intents are enough, or we need to add more
- [x] Update the spec
- [x] Create a ticket for Android
- [x] Create a ticket for web
- [x] Create a ticket for iOS
```

**Comment by Bibisirius** [comment]
1. We provide to add paragraphe 
2. Yes we provide to add intent. We now need to decide whether to add all the colours or just the container colours. To be continued

**Comment by JeremiasUX** [comment]
After talking with the Team we decided to use "Container" colors as intents

**Comment by Bibisirius** [comment]
- [ ] Update the component 
- [ ] Intent container
- [ ] Paragraphe

Waiting for review

**Comment by Bibisirius** [comment]
Figma spec: [url](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=4360-24469&mode=design&t=jlyz0k8CaoQC7vyA-11)

Color intent: 
![Image](https://github.com/adevinta/spark/assets/139967199/d71e4e97-40d5-4a7f-8d19-4fc3082e800b)

**Comment by Bibisirius** [comment]
- [ ] Web : We provide to add intent color container background
- [ ] Android: We provide to add intent color container background
- [ ] iOS : Making available popover and explore the possibility to add intent
