### ISSUE TITLE
[Dropdown] Update Documentation and Components

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1881]
```[tasklist]
### Tasks
- [ ] Update Figma Spec
- [ ] Update ZH Documentation
- [ ] Update Figma Component - rebuild component?
```
