### ISSUE TITLE
[Component] Snackbar

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#1893]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/pull/1894
- [ ] https://github.com/adevinta/spark/pull/1902
- [ ] https://github.com/adevinta/spark/pull/1917
- [ ] https://github.com/adevinta/spark/pull/1916
- [ ] https://github.com/adevinta/spark/pull/1931
- [ ] https://github.com/adevinta/spark/pull/1922
- [ ] https://github.com/adevinta/spark/pull/1979
- [ ] https://github.com/adevinta/spark/pull/1950
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | moderate (component SHOULD be tested by QAA)
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX (see who takes over)
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=43448-28057&mode=design&t=iMUxVHtHP5ksPLW6-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/13HuU0Il5D_KlwWtYZAn-A60R7z9OPKGKuFkCrF0hd80/edit#gid=1926623587)
UATs : | [rich component checklist](https://docs.google.com/spreadsheets/d/1plmBTjbBxT7SyDgrxlRjYHvlS9fYjJVRlGwbpet-HoM/edit#gid=1435862231)

**Comment by soykje** [comment]
@elisa-hery @Bibisirius cc @turolopezsanabria The component is now open for testing: https://spark-ui-uhip-4e6i4lq4v-sparkteams-projects.vercel.app/?path=/docs/experimental-snackbar--docs Happy to discuss 👍

**Comment by elisa-hery** [comment]
Hey @soykje ! Some questions & remarks : 
1. Desktop / chrome & safari & firefox : when you click once on a snackbar, you can drag the snackbar on the screen. Sometimes you can click again and it slide to the left or right, but sometimes you jut never can get rid of it (even if there is a new snackbar showing up, it stays here). Here are some videos :  

- when you cannot drag it and it will never disappear : 

https://github.com/adevinta/spark/assets/142396647/e30fa181-ecd4-48d6-91de-8ebe3eec9857

- when it finally slides on a side :

https://github.com/adevinta/spark/assets/142396647/93fb9101-a049-4f37-86bf-4b4d3dd5a4a8

- when you can have 2 snackbars when the 1st one is blocked : 
<img width="402" alt="Capture d’écran 2024-03-28 à 16 44 12" src="https://github.com/adevinta/spark/assets/142396647/98b45c2c-fee4-4d57-9d4b-61b6e8cae88b">
<br/><br/>
2. I would like to test a long content to see how alignment goes, do you think it will be possible to open a stackblitz or add this case in the storybook ?

<br/><br/>

3. Keyboard navigation : action / close button are well focusable but you have to be super fast to reach the action before it disappears. Is it normal ? On this point, shouldn't we follow the [alert dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/), where the action button should be focusable immediately ? 



https://github.com/adevinta/spark/assets/142396647/86b42d1e-f237-4826-9e37-deece7ef4b18



<br/><br/>
4. about voice over, I'm not sure exactly about how we should test it, I think I would need @Powerplex 's help.

**Comment by elisa-hery** [comment]
Hey @soykje when snackbar content is long, text overflows the action button : 

<img src="https://github.com/adevinta/spark/assets/142396647/c93a3e20-89e5-46de-ad7f-2cb00ba1c8b7" alt="bug" width="600"/>

**Comment by soykje** [comment]
@elisa-hery About your last comment: same as icon issue: flexbox related. I'm gonna update both subcomponents to avoid more noise :+1:

**Comment by soykje** [comment]
As discussed, only first two points remains:
1. A bugfix has been pushed on https://spark-ui-uhip-qqyongusk-sparkteams-projects.vercel.app/?path=/docs/experimental-snackbar--docs
2. Stackblitz playground is up to date (see https://stackblitz.com/edit/stackblitz-starters-gtqgsf?file=pagesContent%2Findex.tsx) with flexbox issue fixed :muscle: 

So afaik everything should be ok now. Please let me know @elisa-hery :pray:

**Comment by elisa-hery** [comment]
@soykje : 
1. I still have issues to swipe on desktop, I can show you live
2. flexbox issue 👌 ✅  

<img src="https://github.com/adevinta/spark/assets/142396647/eb34628a-c9e3-4cba-be66-85983c5a01d2" alt="isolated" width="500"/>

**Comment by elisa-hery** [comment]
@Bibisirius @chuxui --> We would need a design review for this ticket (I'd like to do it live to test the swipe with you)

**Comment by turolopezsanabria** [comment]
Hello, I've just tested snackbar, and sometimes when I slide it it sticks to the cursor but does not leave the page.

https://github.com/adevinta/spark/assets/23620759/c08d4553-9989-459a-9738-1b26a51eb34d

**Comment by elisa-hery** [comment]
The swipe bug is fixed on safari & chrome, mobile & desktop 🥳  thanks @soykje ! 

I have a last remark : 
- on **safari desktop**, when we hover snackbar, cursor is in "text" mode
- still on safari desktop (and I guess it's related), about 1 in 10 times, swiping makes the rest of the text on the page highlighted (see end of video below)

IMO :  if we have a quick way to fix it would be great, however this is not blocking since safari is mainly used on mobile. 
@turolopezsanabria @Bibisirius @chuxui, WDYT ? 

<img width="169" alt="Capture d’écran 2024-04-08 à 14 56 34" src="https://github.com/adevinta/spark/assets/142396647/df85507f-4e24-4ca9-8c53-a166c0c642f0">
<br/><br/>


https://github.com/adevinta/spark/assets/142396647/784857b2-3c6f-4960-bafe-3870a8e16fcc

**Comment by soykje** [comment]
@elisa-hery Here is the final link, with complete fix (included the Safari selection): https://spark-ui-uhip-oak30dxm4-sparkteams-projects.vercel.app/?path=/docs/experimental-snackbar--docs cc @Bibisirius @turolopezsanabria

**Comment by turolopezsanabria** [comment]
Helllo
Can we force the cursor to be `cursor:default;` in this component?
It still looks like `cursor:text;` inside the snackbar

**Comment by soykje** [comment]
@turolopezsanabria I don't have this problem. What browser/OS is it related? Maybe we should then have a look to other components that could benefit the same change, wdyt?

**Comment by turolopezsanabria** [comment]
Sure, I'll check other components

FYI, this video is Safari Version 17.3.1

https://github.com/adevinta/spark/assets/23620759/e0de2d0c-b2cc-407f-9239-8222db30fe33

**Comment by Bibisirius** [comment]
The design is clean.

Regarding the duration: Is it possible to set a custom duration?
 If not, I noticed it's set to 400 in the design specifications but 900 in the test. 400 seems short to me, so I'll go ahead and approve the 900 👍

**Comment by soykje** [comment]
Not sure to understand @Bibisirius. Default timeout value is 5000ms, so within the range of 4000/10000ms defined in [Figma spec](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=43448-28057&mode=design&t=ih7OuAFMHWLbM0GY-0).

You'll see the option in Storybook documentation:

![Image](https://github.com/adevinta/spark/assets/66770550/c4519ae5-b611-4e06-bf49-0436698d7842)

Still, it is completly customisable by consumer, and can be disabled also. Happy to discuss!

**Comment by Bibisirius** [comment]
Alright, Thanks ! It's clear !Sounds good to me 🥇
