### ISSUE TITLE
[Figma Component] Add icon R swap property to button

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1932]
Figma: https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/branch/sy4fVGifUA9zeoJERcCpov/Spark-Components?type=design&mode=design&t=jE8enD1WpIGuGimJ-0

```[tasklist]
### Tasks
- [x] Update the component spinner
- [x] Loading Button: Update the Figma spec
- [x] Loading Button:; Update the ZH spec
```

**Comment by Bibisirius** [comment]
- We provide to follow the size : sm-20px and md-28px
- The current will be resized for the buttons
- Full: We won't be using it


![Image](https://github.com/adevinta/spark/assets/139967199/d9c47ba3-3b7d-4960-bacd-385dc3296161)

**Comment by Bibisirius** [comment]
Next step:

- Update the `Web` spec

**Comment by Bibisirius** [comment]
To be discuted with Web Team

**Comment by Bibisirius** [comment]
Waiting @turolopezsanabria @chuxui @jcatdom double-check the update on the button
