### ISSUE TITLE
[Dropdown] Refine the spec and create the component

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2014]
Refine the spec and create the component
```[tasklist]
### Tasks
- [ ] Refine the spec Figma
- [ ] Create the spec ZH
- [ ] Create the component
```
