### ISSUE TITLE
[Textfield/Input] Update the component 

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2021]
```[tasklist]
### Tasks
- [x] required indicator asterisk went from dim-3 to dim-1 [ticket](https://github.com/adevinta/spark/issues/1956)
- [x] warning and success message are no longer green and yellow
- [x] status indicator (icon) has been removed from: input, textArea, select, dropdown
- [x] We will use the medium-sized icon button by default on all our components dedicated
- [x] the helper text of the input is in "hug" mode, so it's not restrained by the layout
- [x] Replace "show" with " ↪ "
- [x] Update spec Figma and ZH
```

**Comment by JeremiasUX** [comment]
Move to backlog and prio in the next sprint (Q2 - 4 sprint)

**Comment by JeremiasUX** [comment]
Subtask:

- [#2093](https://github.com/adevinta/spark/issues/2093)

**Comment by jcatdom** [comment]
Should we unify clear and lead icons on alignment, spacing and sizing? Comparing Dropdown - Select vs Input vs
![Testing](https://github.com/adevinta/spark/assets/94112525/d39ec9f6-b37a-464c-81e7-f674709dc9da)
 Textarea.

**Comment by Bibisirius** [comment]
Review @ChrisDesignOps

**Comment by ChrisDesignOps** [comment]
Small suggestions in Figma comments to improve the component

**Comment by Bibisirius** [comment]
Ready for review @lauragautheron

**Comment by Bibisirius** [comment]
Note: To be expected: Update the documentation when the colours are changed.
