### ISSUE TITLE
Clean the Specs file

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#2037]
```[tasklist]
### Tasks
- [x] Put the official spec in 0x 0y
- [x] Keep the decisions (black notes) and the past decisions in the official spec
- [x] Create a section, or many sections for exploration, benchmark, brainstorming, tests, etc
```
