### ISSUE TITLE
Search for Broken specs in ZeroHeight

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#2051]
# Task

Search for Broken specs in ZeroHeight
https://spark.adevinta.com/

## Write here what you found

```[tasklist]
### Tasks
- [x] [No content in Foundations > Colors > Design](https://spark.adevinta.com/1186e1705/p/0879a9-colors/b/93226a)
- [x] [The icons preview is broken](https://spark.adevinta.com/1186e1705/p/113df3-iconography)
- [x] [Improve low visibility on Iconography preview image](https://spark.adevinta.com/1186e1705/p/113df3-iconography/b/13c59c/t/page-113df3-87278926-13c59c-7)
- [x] [Foundations > Motion > Review "Try it out" prototype](https://spark.adevinta.com/1186e1705/p/708e8d-motion/b/60fb27/t/page-708e8d-74848733-60fb27-9)
- [x] [Foundations > Motion > Review "Loop" prototype](https://spark.adevinta.com/1186e1705/p/708e8d-motion/b/60fb27/t/page-708e8d-68424220-16)
- [x] [No content in Foundations > z-index > Design](https://spark.adevinta.com/1186e1705/p/071068-z-index/b/26fba8)
- [x] [No content in Components > Components names > Code](https://spark.adevinta.com/1186e1705/p/105a1d-components-names/b/596c2f)
- [x] [No content in Components > Components names > Resources](https://spark.adevinta.com/1186e1705/p/105a1d-components-names/b/696f7f)
```

**Comment by JeremiasUX** [comment]
We will discuss and go through the issue on Tuesday 30th

**Comment by JeremiasUX** [comment]
@ChrisDesignOps is going to fix the first issue in his current task

- No content in Foundations > Colors > Design

**Comment by JeremiasUX** [comment]
Iconography overview broken - check with web devs what kind of icons spark owns (cc: @jcatdom & @andresin87) ([LINK](https://adevinta.zeroheight.com/styleguide/s/100904/p/113df3-iconography))

**Comment by JeremiasUX** [comment]
Iconography design: Move to polaris guide

**Comment by JeremiasUX** [comment]
[Foundations > Motion > Review "Loop" prototype](https://spark.adevinta.com/1186e1705/p/708e8d-motion/b/60fb27/t/page-708e8d-68424220-16)

- Check if we can improve the animation and increase the loading

**Comment by ChrisDesignOps** [comment]
Related to [Foundations > Motion > Review "Loop" prototype](https://spark.adevinta.com/1186e1705/p/708e8d-motion/b/60fb27/t/page-708e8d-68424220-16)
I [asked to Luc](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR?type=design&node-id=10030-1319&mode=design#790142932) the possibility to add a "Refresh button" on "Repeat: 1" prop. 

Or do we assume it without UI? 
I also saw on the Foundations that components for Motion are duplicated, but are applied others on this [Animation DS] for the specs on Figma (https://www.figma.com/file/jUfxTAOU8Oa09ZOvMpyvll/Animation-DS?type=design&node-id=4%3A41&mode=design&t=SEDu5b1vJeGnM1D7-1) file.. (maybe we need another task for clean Motion specs on Figma)

**Comment by jcatdom** [comment]
> Iconography design: Move to polaris guide

@JeremiasUX should we assign it to someone? Or maybe just check it?

**Comment by jcatdom** [comment]
> Related to [Foundations > Motion > Review "Loop" prototype](https://spark.adevinta.com/1186e1705/p/708e8d-motion/b/60fb27/t/page-708e8d-68424220-16) I [asked to Luc](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR?type=design&node-id=10030-1319&mode=design#790142932) the possibility to add a "Refresh button" on "Repeat: 1" prop.
> 
> Or do we assume it without UI? I also saw on the Foundations that components for Motion are duplicated, but are applied others on this [Animation DS](https://www.figma.com/file/jUfxTAOU8Oa09ZOvMpyvll/Animation-DS?type=design&node-id=4%3A41&mode=design&t=SEDu5b1vJeGnM1D7-1) file for the specs on Figma.. (maybe we need another task for clean Motion specs on Figma)

Maybe create related task or subtask in order to move this one to Done

**Comment by JeremiasUX** [comment]
> @JeremiasUX should we assign it to someone? Or maybe just check it?
Yea, just check it. We need to have a clear structure for the Polaris ZH first

**Comment by jcatdom** [comment]
Transfered item to UI team

> Iconography design: Move to polaris guide

[JIRA created to UI team](https://jira.ets.mpi-internal.com/browse/DO-1715)
