### ISSUE TITLE
[Component] Accordion

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#2058]
https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=48556-33536&t=LxwKm786Gyg3IDyR-1

```[tasklist]
### Tasks
- [x] Accordion.Header (web only a11y topic)
- [x] Unit tests
- [ ] Validate animation with Christian
- [x] Multiple mode (open multiple panels)
- [x] Collapsible mode (allow closing all items)
- [x] Collapsible interopability
- [x] Controlled mode (for devs)
- [x] Outlined/Filled designs
- [x] Disabled accordion/Disabled item
```

**Comment by thomas-leguellec** [comment]
Specs are validated:

- [Zeroheight](https://spark.adevinta.com/1186e1705/p/98b03d-accordion)
- [Slack channel](https://adevinta.slack.com/archives/C05SU9ACYJ3/p1718094441414149)

**Comment by Powerplex** [comment]
@elisa-hery @ChrisDesignOps Accordion is ready to be tested here: https://sparkui.vercel.app/?path=/docs/experimental-accordion--docs

**Comment by ChrisDesignOps** [comment]
Test done. Result:
1. Visual: We tolk about setting Accordion item Header with a 44px min-height to be more accessible (currently is 40px) But in [Figma the component](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?m=auto&node-id=15875-32655&t=TEdhd2ga6s44237Y-1) is setted as 48px min-height and I think is better to have a component that breathes more and it's not necessary align the height with the buttons, fields... besides, setted as 44px can be confused with a Select on Mobile.
2. Safari: keyboard navigation doesn’t work.
3. Not directly related to the component: Design example in Dark Theme have two different colors as background.
4. Not directly related to the component: Voiceover screenreader on Storybook doesn’t work. 

The rest seems perfect. 

Pending align the component in Design with the agreements/improvement already applied on the Web component:

* Improve variants: Filled & Outlined (instead border boolean)
* Default design: Outlined
* Focused: Only applied to Header & with the keyboard style (more accessible)
* Specs: Improve first example and considerantions above. Also inform that by default is Outlined and Variant Single item (as the demo)

Tell me if I miss something else. Thx!

**Comment by elisa-hery** [comment]
@ChrisDesignOps about 2. : I think you just need to activate keyboard navigation on safari in your computer's settings : accessibility > keyboard > keyboard settings > switch on "keyboard navigation"

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark/assets/142396647/40a69d7b-6ebd-4415-b897-3daf5cff0c7b" width="500px">
</picture>

**Comment by ChrisDesignOps** [comment]
Thx @elisa-hery! now it works

**Comment by elisa-hery** [comment]
@Powerplex, 2 questions to complete Chris' review : 
1. in the specs I see this option with gaps between the different sections of the accordion but I cannot see it in storybook : is it normal ? Does this variant exist ? 
<picture>
  <img alt="specs" src="https://github.com/adevinta/spark/assets/142396647/5d4ab1ee-a67a-46b9-9c74-6c0adfc9b648" width="400px">
</picture>

2. I noticed that on safari sometimes the hover style stays on a header while another header is selected (not blocking but I just wanted to mention). I reproduce it randomly 



https://github.com/adevinta/spark/assets/142396647/951598ae-2808-454f-a605-c304d12ebddf

info : the list of all that has been checked is [here](https://docs.google.com/spreadsheets/d/18T553y8IsPzQdg10aZyQ0k90GMLDo9pWeE-8eRBWSbk/edit?gid=1926623587#gid=1926623587)

**Comment by Powerplex** [comment]
@elisa-hery about `1` => We discussed between web devs and consider that this example is simply 3 individual accordions with only one item inside each of them. It is more a design guideline that if you have multiple accordions, the gap between them should be `lg`

About `2`, the video is broken I can't play it, but from the thumbnail maybe I can understand: I think you click on a header, which shows the hover style, then you tab to another item, which gets the focus style backgroud, but technically you never left the first one with your mouse so it stays in hover states. Is this it ?

**Comment by elisa-hery** [comment]
about testing alignement : 



![Image](https://github.com/adevinta/spark/assets/142396647/1761a19d-1173-4771-8c74-3cb57d913f52)

**Comment by elisa-hery** [comment]
After sync with @Powerplex & @ChrisDesignOps : 
- everything is almost done, component works great ✅ 
- voiceover does not work on iOS --> @Powerplex will provide an environment for us to be able to test
- the left icon shrinks when there is a long title --> this will be fixed in [this ticket](https://github.com/adevinta/spark/issues/2233) 
- remains updates to do on figma & zeroheight for @ChrisDesignOps

**Comment by elisa-hery** [comment]
- voice over is ok (see video below) ✅



https://github.com/adevinta/spark/assets/142396647/dff8b02b-8bcb-447d-8e97-7afd055f15f2



- the shrink of the icon is fixed and merged. We were able to test this on stackblitz (therefor not on safari) ✅
