### ISSUE TITLE
[Component] - Combobox

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#2066]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/2067
- [ ] https://github.com/adevinta/spark/issues/2068
- [ ] https://github.com/adevinta/spark/issues/2069
- [ ] https://github.com/adevinta/spark/issues/2070
- [ ] https://github.com/adevinta/spark/issues/2071
- [ ] https://github.com/adevinta/spark/issues/2072
- [ ] https://github.com/adevinta/spark/pull/2102
- [ ] https://github.com/adevinta/spark/pull/2103
- [ ] https://github.com/adevinta/spark/pull/2124
- [ ] #2123
- [ ] https://github.com/adevinta/spark/issues/2144
- [ ] https://github.com/adevinta/spark/issues/2142
- [ ] https://github.com/adevinta/spark/issues/2143
```
