### ISSUE TITLE
[Clean Up] Input/texfield

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2093]
- [BAU Clean UP 1705](https://github.com/adevinta/spark/issues/1705)
- Following this ticket: [2021](https://github.com/adevinta/spark/issues/2021)
```[tasklist]
### Tasks
- [ ] Clean Up  Figma Spec
- [ ] Clean Up ZH
- [ ] Update the component
```

**Comment by JeremiasUX** [comment]
Move to backlog and prio in the next sprint (Q2 - 4 sprint)
