### ISSUE TITLE
[Design Spec] Accordion

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2126]
Jira ticket: https://jira.ets.mpi-internal.com/browse/DO-1690

```[tasklist]
### Tasks
- [x] Investigate if we need accordion and collapsible
- [x] Investigate the different platform needs
- [x] Investigate the product use cases
- [x] Spec sheet
- [x] ZH-documentation
- [x] Spark figma component
- [x] Communicate the new component
```

**Comment by ChrisDesignOps** [comment]
✅ **Accordion ready for review**

[ZH specs](https://zeroheight.com/1186e1705/v/latest/p/98b03d-accordion)

[Figma component](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/branch/XbjQNV3KnCktF9jVh7nS0R/Spark-Components?m=auto&node-id=15875-32655&t=4sWZrHtf6jbAiw3M-1)

**Comment by jcatdom** [comment]
✅ Approved

**Comment by ChrisDesignOps** [comment]
✅ Figma component & Specs plublished and communicated
