### ISSUE TITLE
[Design Spec] Collapsible

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2127]
Jira ticket: https://jira.ets.mpi-internal.com/browse/DO-1690

```[tasklist]
### Tasks
- [x] Investigate if we need accordion and collapsible
- [x] Investigate the different platform needs
- [x] Investigate the product use cases
- [x] Spec sheet
- [x] ZH-documentation
- [ ] Spark figma component
- [x] Communicate the new component
```

**Comment by ChrisDesignOps** [comment]
⚠️ **Collapsible is only a behaviour**

1. [ZH specs section](https://spark.adevinta.com/1186e1705/p/98b03d-accordion/t/a2304bcffb) (inside Accordion specs because are directly related)
2. No Figma component

**Comment by ChrisDesignOps** [comment]
✅  Communicated and shared specs about Collapsible behaviour
