### ISSUE TITLE
Adoption GH Action

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#2130]
Convert the adoption script to a public GH action

```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/2131
- [ ] https://github.com/adevinta/spark/pull/2165
- [ ] Add some variables for customize some project settings
- [ ] Configure datadog
- [ ] Send data to datadog storage
- [ ] Configure datadog Dashboard
```
