### ISSUE TITLE
[Textarea] Update the component

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2166]
**Form field needs to be updated:**

-  Discuss if we should remove icons in the text view.

**More info:**

- [Exploration conclusions](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=48127%3A6499&mode=design&t=dRy9kvCpofDmhquM-1) We will share it on the next Spark sharing meeting:
- No external or internal system has a leading & trailing icon in Textview/area.
- As open source system we have to provide the best solutions.
- From Design we don't know now when it was decided to have it in Spark.
- Not native on iOS and may break the component if we customize it.

We have to remove it in Design, Web and Android.
```[tasklist]
### Tasks
- [x] required indicator asterisk went from dim-3 to dim-1 [ticket](https://github.com/adevinta/spark/issues/1956)
- [x] warning and success message are no longer green and yellow
- [x] status indicator (icon) has been removed from: input, textArea, select, dropdown
- [x] We will use the medium-sized icon button by default on all our components dedicated
- [x] Replace "show" with " ↪ "
- [x] Discuss if we should remove icons in the text view (to do)
- [x] Resizer: Can it be removed from the component because it is only available on the Web?
- [x] Update Doc Figma
- [x] Update Doc  ZH
```

**Comment by Bibisirius** [comment]
Ready for review @lauragautheron 
Only Figma spec and component for the moment
