### ISSUE TITLE
[Design Spec] Image

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2171]
The image component is a must deliver component for Android

```[tasklist]
### Tasks
- [x] Investigate the different platform needs
- [x] Investigate the product use cases
- [x] Spec sheet
- [x] Inform via [this ticket](https://github.com/adevinta/spark-android/issues/1076) that devs can start with development
- [x] ZH-documentation
- [x] Spark figma component
- [ ] Communicate the new component
```

**Comment by ChrisDesignOps** [comment]
✅ Image specs [ready in ZH](https://spark.adevinta.com/1186e1705/p/096e9f-image)
Now talking with UI team about the possibility of include as a Figma Component in the Polaris library and not in Spark (adding a description about is an "Android Spark component" this provide unification between platforms about the Image configuration

**Comment by ChrisDesignOps** [comment]
✅ [Image component](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/branch/wNbTTK3iBGcYXdh65Il8ww/Spark-Components?m=auto&node-id=17267-38939&t=XnZ6Cxd5onMdscA8-1) is ready for review

**Comment by ChrisDesignOps** [comment]
✅ [Image component](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?m=auto&node-id=17331-41442&t=rQJrEInEzGjm2I44-1) ready in Spark Figma Library (only for Android)
