### ISSUE TITLE
[Component] - Collapsible (pattern)

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#2177]
### Tasks
- [ ] Zag.js PoC (to get to know zag and provide feedback to other devs) ([Stackblitz](https://stackblitz.com/edit/stackblitz-starters-ybtr9z?file=pagesContent%2Findex.tsx))
- [ ] Radix PoC branch
- [ ] Implement homemade hook to build `Collapsible` (final decision)

```[tasklist]
### Tasks
- [x] Zag.js PoC (to get to know zag and provide feedback to other devs)
- [ ] Radix PoC branch
- [ ] Implement homemade hook to build `Collapsible` (final decision)
```
