### ISSUE TITLE
[Spark Request] Remove max-width restriction

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2194]
We received a request to remove the the max-width for the chip component. We agreed today (04.06.24) that we can remove it and handle this with a guideline.
Request:

- https://jira.ets.mpi-internal.com/browse/DO-1689

The feature is available for:

- Android ✅
- iOS ❌
- Web ✅
- Figma ❌

```[tasklist]
### Tasks
- [x] Update spec in Figma and ZH (remove the max width information)
- [x] Add a "caution" that the max-width should not exceed 240px
- [x] Create dev tickets for Web and Android
- [x] Inform via [this ticket](https://jira.ets.mpi-internal.com/browse/DO-1689) the status of this task
```
