### ISSUE TITLE
[Figma] Check and clean components unpublishing

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2197]
### **🔍 Check and clean up  composants unpublishing**

- Some components are unpublishable on Figma. To have a clean environment, you need to check, clean and publish.
- Take the opportunity to change "show" to "↪️ ".

```[tasklist]
### Tasks
- [x] Dialog/Modal
- [x] Bottom sheet
- [x] Button
- [x] Checkbox
- [x] Chip
- [x] Drawer ((to be publish)
- [x] Icon button
- [x] Popover
- [x] Radio button
- [x] Switch
- [x] Tabs
- [x] Alert dialog
- [x] Badge  Ticket #2234
- [x] Rating
- [x] Spinner
- [x] Progress bar
- [x] Progress tracker verical
- [x] Progress tracker horizontal
- [x] Tag (Ticket #2217
- [x] Snackbar (check with @jcatdom)
- [x] Formfield [spec only ticket #2222]
- [ ] Input [Ticket - #2021] Review
- [ ] Textview/area [Ticket #2166] WIP
```

**Comment by JeremiasUX** [comment]
Last two topics are in progress, this ticket can be closed
