### ISSUE TITLE
validate design tokens with designers

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#277]
```[tasklist]
### Tasks
- [x] Check SUI tokens namespaces (if any are missing on Spark)
- [ ] https://github.com/adevinta/spark/issues/34
- [ ] https://github.com/adevinta/spark/issues/282
- [ ] https://github.com/adevinta/spark/issues/283
- [ ] https://github.com/adevinta/spark/issues/37
- [ ] https://github.com/adevinta/spark/issues/286
- [ ] https://github.com/adevinta/spark/issues/35
- [ ] https://github.com/adevinta/spark/issues/38
- [ ] https://github.com/adevinta/spark/issues/41
- [ ] https://github.com/adevinta/spark/issues/39
- [ ] https://github.com/adevinta/spark/issues/284
- [ ] https://github.com/adevinta/spark/issues/42
- [ ] https://github.com/adevinta/spark/issues/288
```

**Comment by Powerplex** [comment]
Mathieu said they are working on typography now, which will cover: fontFamily, fontSize, fontWeight, lineHeight
