### ISSUE TITLE
[Figma-org] Kickoff - How we work in Polaris with Spark

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#610]
```[tasklist]
### Tasks
- [ ] Polaris ZeroHeight (mathieu + turo)
- [ ] Key Screens (madison + imène)
- [ ] Covers (imène)
- [ ] Tokens (joachim)
- [ ] Workshop figma org (clemence + eli)
```

**Comment by turolopezsanabria** [comment]
Kickoff done on Tuesday
Slack channel to track progress: [#adv-polaris-figma-org](https://adevinta.slack.com/archives/C058BQEL6UR)
