### ISSUE TITLE
[Components] Switch - Adapt to specs

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#618]
```[tasklist]
### Tasks
- [ ] update switch to have default unchecked icon
- [ ] update switch to be aligned to the top when label is multiline
- [ ] ask designers to write down if `hasIcons` is the default mode
- [ ] update props to be able to do the following:
```

<Switch checked>
  switch
</Switch>

<Switch checked checkedIcon={null}>
  switch
</Switch>

<Switch checked checkedIcon={<CustomSVG />} uncheckedIcon={<OtherSVG />}>
  switch
</Switch>

<Switch checked checkedIcon={<CustomSVG />} uncheckedIcon={<OtherSVG />}>
  switch
</Switch>

**Comment by turolopezsanabria** [comment]
✅ OK design review
