### ISSUE TITLE
Induction phase 1: Onboard teams to the CURRENT way of working of a multi tenant environment

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#69]
```[tasklist]
### SUBTASKS
- [ ] Collaboration between UX and Dev
- [ ] Handoff and QA process
- [ ] Figma files and projects organisation
- [ ] Templates and team Libraries
```
