### ISSUE TITLE
[Documentation] Review ZeroHeight - Round 2

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#775]
```[tasklist]
### Tasks
- [x] Spark: Reply Mathieu input
- [x] Polaris: Plan the next steps for Polaris - kickoff
- [x] Spark: Daily
- [x] Spark: Sharings
- [x] Spark: Upload the 2 new icons
- [x] Spark: [doc] All - Remove broken links
- [x] Spark: [doc] All - Remove components status from pages
- [x] Spark: [doc] All - Remove lines between sections
- [x] Spark: [doc] All - Remove bold from H2 and H3
- [x] Spark: [doc] Create here from all comments from Figma
- [x] Spark: [doc] Buttons - Icon sizes
- [x] Spark: [doc] Buttons - Ghost icon alignment
- [x] Spark: [doc] Buttons - Limit shapes for buttons to 3
- [x] Spark: [doc] Buttons - Split hover and pressed
- [x] Spark: [doc] Buttons - Hover and press
- [x] Spark: [doc] Buttons - Inherit size from text
- [x] Spark: [doc] Buttons - Feedback hover + cambio de cursor
- [x] Spark: [doc] Badge - Adds all possible intents, keeping danger (error) as the default one
- [x] Spark: [doc] Badge - Text elements Badges are always "standalone" (inline)
- [x] Spark: [doc] Badge - Screenshots
- [x] Spark: [doc] Badge - Non interactive component
- [x] Spark: [doc] Badge - Without content inside
- [x] Spark: [doc] Badge - Outline instead of Border
- [x] Spark: [doc] Badge - Example for text element + inline badge+
- [x] Spark: [doc] Badge - 99k+ for example
- [x] Spark: [doc] Checkbox - Indetermined in ZH
- [x] Spark: [doc] Checkbox - Intents for Web only
- [x] Spark: [doc] Checkbox - Can't have links in labels - Labels are clickable in Native
- [x] Spark: [doc] Checkbox - Spacing and position of radio and checks validation texts
- [x] Spark: [doc] Checkbox - Spacing Right label space-md - left label is min-width 3xl
- [x] Spark: [doc] Chips - Change name to "closing indicator"
- [x] Spark: [doc] Chips - Rules are too general
- [x] Spark: [doc] Chips - Not a breadcrumb not a pagination
- [x] Spark: [doc] Chips - Most common content in Android will be just the label or icon + label
- [x] Spark: [doc] Chips - Close icon is not available for Android
- [x] Spark: [doc] Chips - 32 height only for desktop 44 for android
- [x] Spark: [doc] Chips - Examples for all kinds of Interactions for Chips
- [x] Spark: [doc] Chips - Ain't a non interactive chip a tag?
- [x] Spark: [doc] Chips - Select a chip last of the list
- [x] Spark: [doc] Chips - Dash
- [x] Spark: [doc] Chips - Non interactive tags
- [x] Spark: [doc] Chips - Any content is allowed
- [x] Spark: [doc] Chips - Closing indicator (read desktop)
- [x] Spark: [doc] Chips - 1st element alignment
- [x] Spark: [doc] Chips - Styles follow the same colour principles as buttons
- [x] Spark: [doc] Chips - just one size for now
- [x] Spark: [doc] Chips - Height calculated dynamically
- [x] Spark: [doc] Chips - CSS reference just for Web
- [x] Spark: [doc] Chips - Selected state
- [x] Spark: [doc] Chips - Mention pressed state follow the same as buttons
- [x] Spark: [doc] Chips - Explain badge inside a chip
- [x] Spark: [doc] Colours - Match Foundation files
- [x] Spark: [doc] Icon - A11y icon on hover - SB
- [x] Spark: [doc] Icon - A11y icon on hover - ZH
- [x] Spark: [doc] Icon - Current-color as default
- [x] Spark: [doc] Icon - Add all available icons from SB in ZH
- [x] Spark: [doc] Icon button - It's on hover that the [a11y](https://m3.material.io/components/icon-buttons/guidelines#47fcd0ba-4390-4d5f-8fe3-905c5795c47f) label is shown - On Android, when we long click on a Icon button we show a tooltip of what the button actions is (validate, more information, delete)
- [x] Spark: [doc] Icon button - We limit to these 3 shapes
- [x] Spark: [doc] Links - Document the approach for links in the documentation
- [x] Spark: [doc] Spinner - Width
- [x] Spark: [doc] Spinner - Android - Leave determinate available as is
- [x] Spark: [doc] Spinner - Always indetermined
- [x] Spark: [doc] Spinner - Restrict colours from the bg
- [x] Spark: [doc] Spinner - Stroke width 2px
- [x] Spark: [doc] Switch - No group of switch
- [x] Spark: [doc] Switch - Default without icons
- [x] Spark: [doc] Switch - Knob draggable in Android
- [x] Spark: [doc] Switch - 200ms in iOS (same as the web), 100ms is too fast)
- [x] Spark: [doc] Switch - Intents only for Web
- [x] Spark: [doc] Switch - Labels are part of switch but not clickable
- [x] Spark: [doc] Switch - Usage rules (check and radio too)
- [x] Spark: [doc] Switch - We can't change the size on Android
- [x] Spark: [doc] Tab - Icon size same as text, If no text icon small
- [x] Spark: [doc] Tab - No arrows for vertical
- [x] Spark: [doc] Tab - No reframe scroll position on resize
- [x] Spark: [doc] Tab - Default space as much with as they need but ...
- [x] Spark: [doc] Tab - Scrollable
- [x] Spark: [doc] Tab - Tab lists on loop
- [x] Spark: [doc] Tab - Icon only
- [x] Spark: [doc] Tag - Sizes
- [x] Spark: [doc] All - Remove links to pages for unfinished components
- [x] Spark: [doc] All - Add links to [Repos](https://github.com/adevinta/spark-android/blob/main/spark/src/main/kotlin/com/adevinta/spark/components/progress/Spinner.md), Figma and else to every component
- [x] Spark: [doc] All - Add all intents
- [x] Spark: [doc] All - Create more tasks from the demos of StoryBook
```

**Comment by turolopezsanabria** [comment]
More things to do in Round 3
https://github.com/adevinta/spark/issues/825
