### ISSUE TITLE
[Figma-org] Polaris ZeroHeight

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#817]
Document all our agreements for Polaris in its ZeroHeight:
Start small, agility is more important than perfection.

Slack channel to track progress: [#adv-polaris-figma-org](https://adevinta.slack.com/archives/C058BQEL6UR)

**In Sprint 9:**

```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/609
- [ ] New icons diagram / process
- [ ] Figma organisation
- [ ] How to deliver specs for Spark (vs Brikke)
- [ ] How to install and use Spark libraries
- [ ] etc
```

**Comment by mathieuhervouetlbc** [comment]
First draft of a Polaris component guideline : https://zeroheight.com/836b236c5/v/latest/p/728bd7-tag/b/32e1a2

**Comment by mathieuhervouetlbc** [comment]
Polaris contribution process : [documentation](https://zeroheight.com/836b236c5/v/latest/p/30ae38-component/b/019254)

**Comment by turolopezsanabria** [comment]
I close this ticket to slice the GitHub in a different way from now on
