### ISSUE TITLE
[Documentation] Review ZeroHeight - Round 3

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#825]
```[tasklist]
### Tasks
- [x] Spark: [doc] All - Add web only in all specs
- [x] Spark: [doc] All - Dos and Don'ts in Context
- [x] Spark: [doc] Chips - Animation transition from M3
```
