### ISSUE TITLE
[Polaris] Tickets being tested in Polaris

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#826]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/118
- [ ] https://github.com/adevinta/spark-ios/issues/77
- [ ] https://github.com/adevinta/spark-ios/issues/44
- [ ] https://github.com/adevinta/spark-ios/issues/33
```
